In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from data_cleaning import *

In [2]:
# Read CSV file 
ev_sales_or_large = pd.read_csv("./CSVs/OREVDashboardData.csv")
ev_sales_or_large

,FirstRegisteredDate,LastRegisteredDate,RegistrationExtensionDate,reg_period,zev_type,Vehicle_ty,exempt_flg,model_year,Make,Model,...,BLKGRPCE,AFFGEOID_1,GEOID_1,ElectricUtility,First Reg Year,New vs Used,NAME10,Senate District,House District,Congressional District
0,"Monday, October 8, 2018","Friday, July 1, 2022","Wednesday, August 28, 2024",2YEAR,EV,Car,0,2018,Tesla,Model 3,...,1.0,1500000US410510093011,4.105100e+11,Portland General Electric,2018,New,Block 1015,24,47,3
1,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Thursday, November 24, 2022",4YEAR,EV,Car,0,2018,Tesla,Model 3,...,2.0,1500000US410510095022,4.105100e+11,Portland General Electric,2019,New,Block 2003,23,45,3
2,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Monday, November 21, 2022",4YEAR,EV,Car,0,2018,Tesla,Model 3,...,2.0,1500000US410510095022,4.105100e+11,Portland General Electric,2019,New,Block 2004,23,45,3
3,"Friday, November 30, 2018","Monday, April 1, 2019","Thursday, September 29, 2022",4YEAR,EV,Car,0,2018,Tesla,Model 3,...,1.0,1500000US410510090001,4.105100e+11,Portland General Electric,2018,New,Block 1009,24,48,3
4,"Thursday, January 10, 2019","Friday, February 1, 2019","Tuesday, December 20, 2022",4YEAR,EV,Car,0,2018,Tesla,Model 3,...,2.0,1500000US410510090002,4.105100e+11,Portland General Electric,2019,New,Block 2010,24,48,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54930,"Thursday, January 17, 2013","Thursday, September 1, 2022","Thursday, November 30, 2023",2YEAR,PHEV,Car,0,2012,Chevrolet,Volt,...,2.0,1500000US410470027002,4.104700e+11,Portland General Electric,2013,New,Block 2059,9,17,6
54931,"Tuesday, October 28, 2014","Thursday, September 1, 2022","Saturday, October 19, 2024",2YEAR,PHEV,Car,0,2014,Ford,C-MAX Energi,...,1.0,1500000US410670324091,4.106700e+11,Portland General Electric,2014,New,Block 1006,15,29,1
54932,"Thursday, November 3, 2011","Thursday, September 1, 2022","Wednesday, May 17, 2023",2YEAR,EV,Car,0,2011,Nissan,LEAF,...,1.0,1500000US410470018031,4.104700e+11,Portland General Electric,2011,New,Block 1009,9,17,6
54933,"Wednesday, August 9, 2017","Thursday, September 1, 2022","Friday, September 6, 2024",2YEAR,PHEV,Car,0,2017,Toyota,Prius Prime,...,2.0,1500000US410670327002,4.106700e+11,Portland General Electric,2017,New,Block 2052,16,31,1
54934,"Friday, July 15, 2016","Thursday, September 1, 2022","Tuesday, July 2, 2024",2YEAR,PHEV,Car,0,2016,Chevrolet,Volt,...,2.0,1500000US410510089012,4.105100e+11,Portland General Electric,2016,New,Block 2010,24,48,3

In [3]:
# Get all information about DataFrame 
checking_dataframe(ev_sales_or_large)

DataFrame Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54935 entries, 0 to 54934
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   FirstRegisteredDate        54935 non-null  object
 1   LastRegisteredDate         54935 non-null  object
 2   RegistrationExtensionDate  54033 non-null  object
 3   reg_period                 54628 non-null  object
 4   zev_type                   54935 non-null  object
 5   Vehicle_ty                 54935 non-null  object
 6   exempt_flg                 54935 non-null  int64
 7   model_year                 54935 non-null  int64
 8   Make                       54935 non-null  object
 9   Model                      54935 non-null  object
 10  AvgGrossVehicleWeight      54935 non-null  float64
 11  ave_MPG                    54935 non-null  int64
 12  ave_mo_vmt                 237 non-null    float64
 13  County                     54933 non-null  object
 14  City                       54932 non-null  object
 15  Zip                        54935 non-null  int64
 16  State                      54933 non-null  object
 17  Index_                     54935 non-null  int64
 18  County_GIS                 54638 non-null  object
 19  SubCounty                  54638 non-null  object
 20  TRACTCE10                  54638 non-null  float64
 21  BLOCKCE10                  54638 non-null  float64
 22  GEOID10                    54638 non-null  float64
 23  TRACTCE                    54638 non-null  float64
 24  BLKGRPCE                   54638 non-null  float64
 25  AFFGEOID_1                 54638 non-null  object
 26  GEOID_1                    54638 non-null  float64
 27  ElectricUtility            54638 non-null  object
 28  First Reg Year             54935 non-null  int64
 29  New vs Used                54935 non-null  object
 30  NAME10                     54638 non-null  object
 31  Senate District            54935 non-null  int64
 32  House District             54935 non-null  int64
 33  Congressional District     54935 non-null  int64
dtypes: float64(8), int64(9), object(17)
memory usage: 14.3+ MB
None

Data Types

FirstRegisteredDate           object
LastRegisteredDate            object
RegistrationExtensionDate     object
reg_period                    object
zev_type                      object
Vehicle_ty                    object
exempt_flg                     int64
model_year                     int64
Make                          object
Model                         object
AvgGrossVehicleWeight        float64
ave_MPG                        int64
ave_mo_vmt                   float64
County                        object
City                          object
Zip                            int64
State                         object
Index_                         int64
County_GIS                    object
SubCounty                     object
TRACTCE10                    float64
BLOCKCE10                    float64
GEOID10                      float64
TRACTCE                      float64
BLKGRPCE                     float64
AFFGEOID_1                    object
GEOID_1                      float64
ElectricUtility               object
First Reg Year                 int64
New vs Used                   object
NAME10                        object
Senate District                int64
House District                 int64
Congressional District         int64
dtype: object

Null Values

FirstRegisteredDate              0
LastRegisteredDate               0
RegistrationExtensionDate      902
reg_period                     307
zev_type                         0
Vehicle_ty                       0
exempt_flg                       0
model_year                       0
Make                             0
Model                            0
AvgGrossVehicleWeight            0
ave_MPG                          0
ave_mo_vmt                   54698
County                           2
City                             3
Zip                              0
State                            2
Index_                           0
County_GIS                     297
SubCounty                      297
TRACTCE10                      297
BLOCKCE10                      297
GEOID10                        297
TRACTCE                        297
BLKGRPCE                       297
AFFGEOID_1                     297
GEOID_1                        297
ElectricUtility                297
First Reg Year                   0
New vs Used                      0
NAME10                         297
Senate District                  0
House District                   0
Congressional District           0
dtype: int64

In [4]:
# Remove Columns

clean_ev_sales_or_large = ev_sales_or_large.drop(['reg_period','ave_mo_vmt','County_GIS','SubCounty','TRACTCE10','BLOCKCE10','GEOID10',
                       'TRACTCE','BLKGRPCE','AFFGEOID_1','GEOID_1','NAME10','Senate District','House District',
                       'Congressional District','exempt_flg','Index_' ], axis=1)

clean_ev_sales_or_large

,FirstRegisteredDate,LastRegisteredDate,RegistrationExtensionDate,zev_type,Vehicle_ty,model_year,Make,Model,AvgGrossVehicleWeight,ave_MPG,County,City,Zip,State,ElectricUtility,First Reg Year,New vs Used
0,"Monday, October 8, 2018","Friday, July 1, 2022","Wednesday, August 28, 2024",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2018,New
1,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Thursday, November 24, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
2,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Monday, November 21, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
3,"Friday, November 30, 2018","Monday, April 1, 2019","Thursday, September 29, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2018,New
4,"Thursday, January 10, 2019","Friday, February 1, 2019","Tuesday, December 20, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2019,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54930,"Thursday, January 17, 2013","Thursday, September 1, 2022","Thursday, November 30, 2023",PHEV,Car,2012,Chevrolet,Volt,4583.00,94,MARION,TURNER,97392,OR,Portland General Electric,2013,New
54931,"Tuesday, October 28, 2014","Thursday, September 1, 2022","Saturday, October 19, 2024",PHEV,Car,2014,Ford,C-MAX Energi,5201.47,88,WASHINGTON,HILLSBORO,97123,OR,Portland General Electric,2014,New
54932,"Thursday, November 3, 2011","Thursday, September 1, 2022","Wednesday, May 17, 2023",EV,Car,2011,Nissan,LEAF,4322.00,87,MARION,SALEM,97317,OR,Portland General Electric,2011,New
54933,"Wednesday, August 9, 2017","Thursday, September 1, 2022","Friday, September 6, 2024",PHEV,Car,2017,Toyota,Prius Prime,4535.62,133,WASHINGTON,NORTH PLAINS,97133,OR,Portland General Electric,2017,New
54934,"Friday, July 15, 2016","Thursday, September 1, 2022","Tuesday, July 2, 2024",PHEV,Car,2016,Chevrolet,Volt,4775.54,106,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2016,New

In [5]:
# Clening column names 
clean_columns(clean_ev_sales_or_large)
clean_ev_sales_or_large

,Firstregistereddate,Lastregistereddate,Registrationextensiondate,Zev_Type,Vehicle_Ty,Model_Year,Make,Model,Avggrossvehicleweight,Ave_Mpg,County,City,Zip,State,Electricutility,First_Reg_Year,New_Vs_Used
0,"Monday, October 8, 2018","Friday, July 1, 2022","Wednesday, August 28, 2024",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2018,New
1,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Thursday, November 24, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
2,"Tuesday, January 1, 2019","Tuesday, January 1, 2019","Monday, November 21, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
3,"Friday, November 30, 2018","Monday, April 1, 2019","Thursday, September 29, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2018,New
4,"Thursday, January 10, 2019","Friday, February 1, 2019","Tuesday, December 20, 2022",EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2019,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54930,"Thursday, January 17, 2013","Thursday, September 1, 2022","Thursday, November 30, 2023",PHEV,Car,2012,Chevrolet,Volt,4583.00,94,MARION,TURNER,97392,OR,Portland General Electric,2013,New
54931,"Tuesday, October 28, 2014","Thursday, September 1, 2022","Saturday, October 19, 2024",PHEV,Car,2014,Ford,C-MAX Energi,5201.47,88,WASHINGTON,HILLSBORO,97123,OR,Portland General Electric,2014,New
54932,"Thursday, November 3, 2011","Thursday, September 1, 2022","Wednesday, May 17, 2023",EV,Car,2011,Nissan,LEAF,4322.00,87,MARION,SALEM,97317,OR,Portland General Electric,2011,New
54933,"Wednesday, August 9, 2017","Thursday, September 1, 2022","Friday, September 6, 2024",PHEV,Car,2017,Toyota,Prius Prime,4535.62,133,WASHINGTON,NORTH PLAINS,97133,OR,Portland General Electric,2017,New
54934,"Friday, July 15, 2016","Thursday, September 1, 2022","Tuesday, July 2, 2024",PHEV,Car,2016,Chevrolet,Volt,4775.54,106,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2016,New

In [6]:
# Remove whitespace from entire Dataframe
clean_ev_sales_or_large.applymap(remove_whitespace)

,Firstregistereddate,Lastregistereddate,Registrationextensiondate,Zev_Type,Vehicle_Ty,Model_Year,Make,Model,Avggrossvehicleweight,Ave_Mpg,County,City,Zip,State,Electricutility,First_Reg_Year,New_Vs_Used
0,"Monday,October8,2018","Friday,July1,2022","Wednesday,August28,2024",EV,Car,2018,Tesla,Model3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,PortlandGeneralElectric,2018,New
1,"Tuesday,January1,2019","Tuesday,January1,2019","Thursday,November24,2022",EV,Car,2018,Tesla,Model3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,PortlandGeneralElectric,2019,New
2,"Tuesday,January1,2019","Tuesday,January1,2019","Monday,November21,2022",EV,Car,2018,Tesla,Model3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,PortlandGeneralElectric,2019,New
3,"Friday,November30,2018","Monday,April1,2019","Thursday,September29,2022",EV,Car,2018,Tesla,Model3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,PortlandGeneralElectric,2018,New
4,"Thursday,January10,2019","Friday,February1,2019","Tuesday,December20,2022",EV,Car,2018,Tesla,Model3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,PortlandGeneralElectric,2019,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54930,"Thursday,January17,2013","Thursday,September1,2022","Thursday,November30,2023",PHEV,Car,2012,Chevrolet,Volt,4583.00,94,MARION,TURNER,97392,OR,PortlandGeneralElectric,2013,New
54931,"Tuesday,October28,2014","Thursday,September1,2022","Saturday,October19,2024",PHEV,Car,2014,Ford,C-MAXEnergi,5201.47,88,WASHINGTON,HILLSBORO,97123,OR,PortlandGeneralElectric,2014,New
54932,"Thursday,November3,2011","Thursday,September1,2022","Wednesday,May17,2023",EV,Car,2011,Nissan,LEAF,4322.00,87,MARION,SALEM,97317,OR,PortlandGeneralElectric,2011,New
54933,"Wednesday,August9,2017","Thursday,September1,2022","Friday,September6,2024",PHEV,Car,2017,Toyota,PriusPrime,4535.62,133,WASHINGTON,NORTHPLAINS,97133,OR,PortlandGeneralElectric,2017,New
54934,"Friday,July15,2016","Thursday,September1,2022","Tuesday,July2,2024",PHEV,Car,2016,Chevrolet,Volt,4775.54,106,MULTNOMAH,PORTLAND,97236,OR,PortlandGeneralElectric,2016,New

In [7]:
# Drop Null Values
clean_ev_sales_or_large = clean_ev_sales_or_large.dropna()
checking_dataframe(clean_ev_sales_or_large)

DataFrame Information

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53735 entries, 0 to 54934
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Firstregistereddate        53735 non-null  object
 1   Lastregistereddate         53735 non-null  object
 2   Registrationextensiondate  53735 non-null  object
 3   Zev_Type                   53735 non-null  object
 4   Vehicle_Ty                 53735 non-null  object
 5   Model_Year                 53735 non-null  int64
 6   Make                       53735 non-null  object
 7   Model                      53735 non-null  object
 8   Avggrossvehicleweight      53735 non-null  float64
 9   Ave_Mpg                    53735 non-null  int64
 10  County                     53735 non-null  object
 11  City                       53735 non-null  object
 12  Zip                        53735 non-null  int64
 13  State                      53735 non-null  object
 14  Electricutility            53735 non-null  object
 15  First_Reg_Year             53735 non-null  int64
 16  New_Vs_Used                53735 non-null  object
dtypes: float64(1), int64(4), object(12)
memory usage: 7.4+ MB
None

Data Types

Firstregistereddate           object
Lastregistereddate            object
Registrationextensiondate     object
Zev_Type                      object
Vehicle_Ty                    object
Model_Year                     int64
Make                          object
Model                         object
Avggrossvehicleweight        float64
Ave_Mpg                        int64
County                        object
City                          object
Zip                            int64
State                         object
Electricutility               object
First_Reg_Year                 int64
New_Vs_Used                   object
dtype: object

Null Values

Firstregistereddate          0
Lastregistereddate           0
Registrationextensiondate    0
Zev_Type                     0
Vehicle_Ty                   0
Model_Year                   0
Make                         0
Model                        0
Avggrossvehicleweight        0
Ave_Mpg                      0
County                       0
City                         0
Zip                          0
State                        0
Electricutility              0
First_Reg_Year               0
New_Vs_Used                  0
dtype: int64

In [8]:
# Use pandas.to_datetime() to convert string to datetime format
pd.options.mode.chained_assignment = None
clean_ev_sales_or_large["Firstregistereddate"] = pd.to_datetime(clean_ev_sales_or_large["Firstregistereddate"])
clean_ev_sales_or_large["Lastregistereddate"] = pd.to_datetime(clean_ev_sales_or_large["Lastregistereddate"])
clean_ev_sales_or_large["Registrationextensiondate"] = pd.to_datetime(clean_ev_sales_or_large["Registrationextensiondate"])

clean_ev_sales_or_large

,Firstregistereddate,Lastregistereddate,Registrationextensiondate,Zev_Type,Vehicle_Ty,Model_Year,Make,Model,Avggrossvehicleweight,Ave_Mpg,County,City,Zip,State,Electricutility,First_Reg_Year,New_Vs_Used
0,2018-10-08,2022-07-01,2024-08-28,EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2018,New
1,2019-01-01,2019-01-01,2022-11-24,EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
2,2019-01-01,2019-01-01,2022-11-21,EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
3,2018-11-30,2019-04-01,2022-09-29,EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2018,New
4,2019-01-10,2019-02-01,2022-12-20,EV,Car,2018,Tesla,Model 3,4072.00,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2019,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54930,2013-01-17,2022-09-01,2023-11-30,PHEV,Car,2012,Chevrolet,Volt,4583.00,94,MARION,TURNER,97392,OR,Portland General Electric,2013,New
54931,2014-10-28,2022-09-01,2024-10-19,PHEV,Car,2014,Ford,C-MAX Energi,5201.47,88,WASHINGTON,HILLSBORO,97123,OR,Portland General Electric,2014,New
54932,2011-11-03,2022-09-01,2023-05-17,EV,Car,2011,Nissan,LEAF,4322.00,87,MARION,SALEM,97317,OR,Portland General Electric,2011,New
54933,2017-08-09,2022-09-01,2024-09-06,PHEV,Car,2017,Toyota,Prius Prime,4535.62,133,WASHINGTON,NORTH PLAINS,97133,OR,Portland General Electric,2017,New
54934,2016-07-15,2022-09-01,2024-07-02,PHEV,Car,2016,Chevrolet,Volt,4775.54,106,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2016,New

In [9]:
# Check the Data Types
clean_ev_sales_or_large.dtypes

Firstregistereddate          datetime64[ns]
Lastregistereddate           datetime64[ns]
Registrationextensiondate    datetime64[ns]
Zev_Type                             object
Vehicle_Ty                           object
Model_Year                            int64
Make                                 object
Model                                object
Avggrossvehicleweight               float64
Ave_Mpg                               int64
County                               object
City                                 object
Zip                                   int64
State                                object
Electricutility                      object
First_Reg_Year                        int64
New_Vs_Used                          object
dtype: object

In [10]:
# Rename specific column names
pd.options.mode.chained_assignment = None
clean_ev_sales_or_large.rename(columns={'Firstregistereddate':'First_Reg_Date','Lastregistereddate':'Last_Reg_Date',
                                        'Registrationextensiondate':'Reg_Extn_Date'}, inplace=True)

clean_ev_sales_or_large.head()

,First_Reg_Date,Last_Reg_Date,Reg_Extn_Date,Zev_Type,Vehicle_Ty,Model_Year,Make,Model,Avggrossvehicleweight,Ave_Mpg,County,City,Zip,State,Electricutility,First_Reg_Year,New_Vs_Used
0,2018-10-08,2022-07-01,2024-08-28,EV,Car,2018,Tesla,Model 3,4072.0,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2018,New
1,2019-01-01,2019-01-01,2022-11-24,EV,Car,2018,Tesla,Model 3,4072.0,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
2,2019-01-01,2019-01-01,2022-11-21,EV,Car,2018,Tesla,Model 3,4072.0,116,MULTNOMAH,PORTLAND,97230,OR,Portland General Electric,2019,New
3,2018-11-30,2019-04-01,2022-09-29,EV,Car,2018,Tesla,Model 3,4072.0,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2018,New
4,2019-01-10,2019-02-01,2022-12-20,EV,Car,2018,Tesla,Model 3,4072.0,116,MULTNOMAH,PORTLAND,97236,OR,Portland General Electric,2019,New

In [11]:
# Total number of vehicle sold by type 
clean_ev_sales_or_large["Vehicle_Ty"].value_counts()

Car                 42134
SUV                  9823
Van                  1074
Motorcycle            431
Low-Speed Car         122
Moped                  81
Truck                  66
Medium-Speed Car        4
Name: Vehicle_Ty, dtype: int64

In [12]:
# Total number of EV and ZEV vehicles sales in Oregon
clean_ev_sales_or_large["Zev_Type"].value_counts()

EV      35140
PHEV    18595
Name: Zev_Type, dtype: int64

In [21]:
# Top 5 EV makers in Oregon
clean_ev_sales_or_large["Make"].value_counts().head()

Tesla        17445
Nissan        5978
Chevrolet     5891
Toyota        5450
Ford          3275
Name: Make, dtype: int64

In [22]:
# Top 5 EV model sales in Oregon
clean_ev_sales_or_large["Model"].value_counts().head()

Model 3        8182
LEAF           5978
Model Y        5190
Bolt EV        2706
Prius Prime    2686
Name: Model, dtype: int64

In [13]:
# Countrywise EV sales by makers
countywise_make = clean_ev_sales_or_large.groupby(['County','Make']).size()
display(countywise_make)

County   Make
BAKER    BMW             1
         Chevrolet       6
         Chrysler        1
         FIAT            1
         Ford            3
                      ...
YAMHILL  Toyota        120
         Volkswagen     23
         Volvo          18
         ZAPP            1
         ZERO            2
Length: 942, dtype: int64

In [14]:
# Write clean CSV file
clean_ev_sales_or_large.to_csv("./CSVs/clean_datasets/ev_sales_or_large.csv",index=False)