In [28]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

In [29]:
from google.colab import files
 
 
uploaded = files.upload()

In [30]:
# Read CSV file to DataFrame
vehicles_df = pd.read_csv("all_alpha_22 (3).csv",encoding='utf-8')
vehicles_df.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay,Comb CO2
0,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,NHNXV02.4KH3,small car,3,24,34,28,6,No,316
1,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,NHNXV02.4KH3,small car,3,24,34,28,6,No,316
2,ACURA MDX,3.5,6.0,SemiAuto-10,2WD,Gasoline,CA,L3ULEV70,California LEV-III ULEV70,NHNXT03.5CCC,small SUV,5,19,26,22,5,No,411
3,ACURA MDX,3.5,6.0,SemiAuto-10,2WD,Gasoline,FA,T3B70,Federal Tier 3 Bin 70,NHNXT03.5CCC,small SUV,5,19,26,22,5,No,411
4,ACURA MDX,3.5,6.0,SemiAuto-10,4WD,Gasoline,CA,L3ULEV70,California LEV-III ULEV70,NHNXT03.5CCC,small SUV,5,19,25,21,4,No,423

In [31]:
# Drop duplicates form Dataframe
vehicles_df.drop_duplicates()

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay,Comb CO2
0,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,NHNXV02.4KH3,small car,3,24,34,28,6,No,316
1,ACURA ILX,2.4,4.0,AMS-8,2WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,NHNXV02.4KH3,small car,3,24,34,28,6,No,316
2,ACURA MDX,3.5,6.0,SemiAuto-10,2WD,Gasoline,CA,L3ULEV70,California LEV-III ULEV70,NHNXT03.5CCC,small SUV,5,19,26,22,5,No,411
3,ACURA MDX,3.5,6.0,SemiAuto-10,2WD,Gasoline,FA,T3B70,Federal Tier 3 Bin 70,NHNXT03.5CCC,small SUV,5,19,26,22,5,No,411
4,ACURA MDX,3.5,6.0,SemiAuto-10,4WD,Gasoline,CA,L3ULEV70,California LEV-III ULEV70,NHNXT03.5CCC,small SUV,5,19,25,21,4,No,423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,VOLVO XC90 T6,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,T3B30,Federal Tier 3 Bin 30,NVVXJ02.0S32,standard SUV,7,19,27,22,5,No,405
2623,VOLVO XC90 T8 Recharge,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,L3SULEV30,California LEV-III SULEV30,NVVXJ02.0P3S,standard SUV,7,26/58,28/53,27/55,9,Yes,197
2624,VOLVO XC90 T8 Recharge,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,T3B30,Federal Tier 3 Bin 30,NVVXJ02.0P3S,standard SUV,7,26/58,28/53,27/55,9,Yes,197
2625,VOLVO XC90 T8 Recharge ext. Range,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,L3SULEV30,California LEV-III SULEV30,NVVXJ02.0P3L,standard SUV,7,25/64,27/68,26/66,10,Yes,131
2626,VOLVO XC90 T8 Recharge ext. Range,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,T3B30,Federal Tier 3 Bin 30,NVVXJ02.0P3L,standard SUV,7,25/64,27/68,26/66,10,Yes,131

In [32]:
# Create a new DataFrame with desired columns
data = { 'Fuel': vehicles_df['Fuel'], 
        'Greenhouse_Score':vehicles_df['Greenhouse Gas Score'],'Comb_Co2':vehicles_df['Comb CO2'],
        'SmartWay':vehicles_df['SmartWay']}
smart_vehicles_df = pd.DataFrame(data)
smart_vehicles_df.head()

       Fuel  Greenhouse_Score Comb_Co2 SmartWay
0  Gasoline                 6      316       No
1  Gasoline                 6      316       No
2  Gasoline                 5      411       No
3  Gasoline                 5      411       No
4  Gasoline                 4      423       No

In [33]:
# Clean "Cobm_Co2" data
smart_vehicles_df['Comb_Co2'] = smart_vehicles_df['Comb_Co2'].str.split('/').str[0]

In [34]:
# Convert "Comb_Co2" data type to integer
smart_vehicles_df['Comb_Co2'] = smart_vehicles_df['Comb_Co2'].astype(str).astype(int)
smart_vehicles_df.dtypes

Fuel                object
Greenhouse_Score     int64
Comb_Co2             int64
SmartWay            object
dtype: object

In [35]:
# Using map function
smart_vehicles_df['SmartWay'] = smart_vehicles_df['SmartWay'].replace('Elite','Yes')
smart_vehicles_df['SmartWay'] = smart_vehicles_df['SmartWay'].map({'Yes': 1, 'No': 0})
smart_vehicles_df

                      Fuel  Greenhouse_Score  Comb_Co2  SmartWay
0                 Gasoline                 6       316         0
1                 Gasoline                 6       316         0
2                 Gasoline                 5       411         0
3                 Gasoline                 5       411         0
4                 Gasoline                 4       423         0
...                    ...               ...       ...       ...
2622              Gasoline                 5       405         0
2623  Gasoline/Electricity                 9       197         1
2624  Gasoline/Electricity                 9       197         1
2625  Gasoline/Electricity                10       131         1
2626  Gasoline/Electricity                10       131         1

[2627 rows x 4 columns]

In [36]:
# # Encode "Fuel" column
from sklearn.preprocessing import OneHotEncoder
# one hot encoding
enc = OneHotEncoder(sparse=False)
fuel_onehot = enc.fit_transform(smart_vehicles_df[['Fuel']])
#to print the encoded features for train data
fuel_encoded_df = pd.DataFrame(fuel_onehot, columns=list(enc.categories_[0]))
fuel_encoded_df["Greenhouse_Score"] = smart_vehicles_df["Greenhouse_Score"]
fuel_encoded_df["Comb_CO2"] = smart_vehicles_df["Comb_Co2"]
fuel_encoded_df["SmartWay"] = smart_vehicles_df["SmartWay"]
fuel_encoded_df

,Diesel,Electricity,Ethanol/Gas,Gasoline,Gasoline/Electricity,Hydrogen,Greenhouse_Score,Comb_CO2,SmartWay
0,0.0,0.0,0.0,1.0,0.0,0.0,6,316,0
1,0.0,0.0,0.0,1.0,0.0,0.0,6,316,0
2,0.0,0.0,0.0,1.0,0.0,0.0,5,411,0
3,0.0,0.0,0.0,1.0,0.0,0.0,5,411,0
4,0.0,0.0,0.0,1.0,0.0,0.0,4,423,0
...,...,...,...,...,...,...,...,...,...
2622,0.0,0.0,0.0,1.0,0.0,0.0,5,405,0
2623,0.0,0.0,0.0,0.0,1.0,0.0,9,197,1
2624,0.0,0.0,0.0,0.0,1.0,0.0,9,197,1
2625,0.0,0.0,0.0,0.0,1.0,0.0,10,131,1
2626,0.0,0.0,0.0,0.0,1.0,0.0,10,131,1

In [37]:
# Get X and y
X = fuel_encoded_df.iloc[:, :-1]
y = pd.DataFrame(fuel_encoded_df.iloc[:, -1])
y

      SmartWay
0            0
1            0
2            0
3            0
4            0
...        ...
2622         0
2623         1
2624         1
2625         1
2626         1

[2627 rows x 1 columns]

In [38]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
X_train

(2101, 8)
(526, 8)
(2101, 1)
(526, 1)

,Diesel,Electricity,Ethanol/Gas,Gasoline,Gasoline/Electricity,Hydrogen,Greenhouse_Score,Comb_CO2
1735,0.0,0.0,0.0,1.0,0.0,0.0,3,495
1732,0.0,0.0,0.0,1.0,0.0,0.0,3,560
1136,0.0,0.0,0.0,1.0,0.0,0.0,7,243
1663,0.0,0.0,0.0,1.0,0.0,0.0,5,385
440,0.0,0.0,0.0,1.0,0.0,0.0,2,573
...,...,...,...,...,...,...,...,...
1731,0.0,0.0,0.0,1.0,0.0,0.0,3,560
763,0.0,0.0,0.0,1.0,0.0,0.0,5,388
835,0.0,0.0,1.0,0.0,0.0,0.0,4,399
1653,0.0,0.0,0.0,1.0,0.0,0.0,8,225
2607,0.0,1.0,0.0,0.0,0.0,0.0,10,0

In [39]:
# Preprocess numerical data for neural network

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [40]:
# Define the basic neural network model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=8))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
66/66 [==============================] - 1s 2ms/step - loss: 0.6478 - accuracy: 0.6797
Epoch 2/50
66/66 [==============================] - 0s 2ms/step - loss: 0.4518 - accuracy: 0.9300
Epoch 3/50
66/66 [==============================] - 0s 2ms/step - loss: 0.3253 - accuracy: 0.9638
Epoch 4/50
66/66 [==============================] - 0s 2ms/step - loss: 0.2372 - accuracy: 0.9576
Epoch 5/50
66/66 [==============================] - 0s 2ms/step - loss: 0.1820 - accuracy: 0.9529
Epoch 6/50
66/66 [==============================] - 0s 2ms/step - loss: 0.1478 - accuracy: 0.9500
Epoch 7/50
66/66 [==============================] - 0s 2ms/step - loss: 0.1265 - accuracy: 0.9486
Epoch 8/50
66/66 [==============================] - 0s 2ms/step - loss: 0.1124 - accuracy: 0.9553
Epoch 9/50
66/66 [==============================] - 0s 2ms/step - loss: 0.1025 - accuracy: 0.9543
Epoch 10/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0949 - accuracy: 0.9557
Epoch 11/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0892 - accuracy: 0.9567
Epoch 12/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0846 - accuracy: 0.9629
Epoch 13/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9619
Epoch 14/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0775 - accuracy: 0.9624
Epoch 15/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0749 - accuracy: 0.9638
Epoch 16/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0731 - accuracy: 0.9676
Epoch 17/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0712 - accuracy: 0.9643
Epoch 18/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0698 - accuracy: 0.9657
Epoch 19/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0687 - accuracy: 0.9653
Epoch 20/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0678 - accuracy: 0.9657
Epoch 21/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0669 - accuracy: 0.9672
Epoch 22/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0660 - accuracy: 0.9648
Epoch 23/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0653 - accuracy: 0.9672
Epoch 24/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0649 - accuracy: 0.9676
Epoch 25/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0643 - accuracy: 0.9667
Epoch 26/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0639 - accuracy: 0.9672
Epoch 27/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0632 - accuracy: 0.9667
Epoch 28/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0632 - accuracy: 0.9662
Epoch 29/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0626 - accuracy: 0.9681
Epoch 30/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0623 - accuracy: 0.9681
Epoch 31/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0621 - accuracy: 0.9657
Epoch 32/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0616 - accuracy: 0.9672
Epoch 33/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0612 - accuracy: 0.9705
Epoch 34/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0609 - accuracy: 0.9662
Epoch 35/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0609 - accuracy: 0.9662
Epoch 36/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0605 - accuracy: 0.9695
Epoch 37/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0604 - accuracy: 0.9710
Epoch 38/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0601 - accuracy: 0.9686
Epoch 39/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0600 - accuracy: 0.9686
Epoch 40/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0599 - accuracy: 0.9714
Epoch 41/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0595 - accuracy: 0.9691
Epoch 42/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0596 - accuracy: 0.9657
Epoch 43/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0597 - accuracy: 0.9710
Epoch 44/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0592 - accuracy: 0.9700
Epoch 45/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0591 - accuracy: 0.9724
Epoch 46/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0590 - accuracy: 0.9714
Epoch 47/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0591 - accuracy: 0.9700
Epoch 48/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0589 - accuracy: 0.9705
Epoch 49/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0587 - accuracy: 0.9714
Epoch 50/50
66/66 [==============================] - 0s 2ms/step - loss: 0.0587 - accuracy: 0.9743
17/17 - 0s - loss: 0.0940 - accuracy: 0.9506 - 130ms/epoch - 8ms/step
Loss: 0.09397619962692261, Accuracy: 0.9505703449249268